name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches:
      - master  # or 'main' if that's your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4  # Updated to v4 for Node 20

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to v4 for Node 20
        with:
          node-version: '16'  # This is for your project setup, can be 16 or 18 if needed

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
